### ISSUE TITLE
设置中的选择题答案是否只支持已作答完毕的题目？

### ISSUE THREAD

**Issue by greenredstone** [PillarsZhang/Rain-Classroom-PDF-Direct-Download#4]
导出的pdf没有答案

**Comment by PillarsZhang** [comment]
你说的应该是“课件”，这个目前是不支持
不过理想情况下，输出的PDF应该和页面显示的一致（有对错标记），这是 html2canvas 的原因，更新它的版本或许能解决
不行我只能按顺序对齐外面的答案和PPT页码了（课堂类型是依赖图片链接的比较）
有空我会更新一下

**Comment by greenredstone** [comment]
好的
