### ISSUE TITLE
Output files are extrodinarily large, should further compress during creation

### ISSUE THREAD

**Issue by rtsui-harmonicinc** [PillarsZhang/Rain-Classroom-PDF-Direct-Download#5]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/11556527/200594308-fe513fa0-d521-43f9-afc5-77c7863927ae.png">
For each lecture having 50-100 slides, many of the files are taking around 50MB to 200MB.

Tried using ghostscipt to compress the file, which would increase the file size instead.
At last I am settled with imagemagick's convert, as suggested from here [link](https://askubuntu.com/questions/113544/how-can-i-reduce-the-file-size-of-a-scanned-pdf-file).

`convert -density 200x200 -quality 60 -compress jpeg input.pdf output.pdf`
This made the files ~10x smaller than original.

**Comment by PillarsZhang** [comment]
Thank you for your solution.
The size of the slide image on the web page is not fixed, so the plug-in will retain its original size and use lossless compression to ensure image quality.
Maybe the slide properties or device compatibility are different. I didn't find any problems during the test.
At present, I prefer to use special tools (like [ImageMagick](https://www.imagemagick.org/) you mentioned) to compress PDF after downloading files.
It is a challenge to implement pdf compression and balance quality and size on the front end.
